# Project information
site_name: "IHC - Fórum TutorBrasil"
site_author: "Grupo 07"
site_url: "https://luisgaboardi.github.io/Forum-TutorBrasil"

# Repository
repo_name: "Fórum TutorBrasil"
repo_url: "https://github.com/luisgaboardi/Forum-TutorBrasil"

theme: readthedocs

# Content Menu
nav:
  - Projeto:
      - Requisitos:
        - alguma coisa: "nada.md"
      - Design:
          - Identidade visual: "project/visual-identity.md"
          - Protótipo de baixa fidelidade: "project/low-prototype.md"
          - Protótipo de média fidelidade: "project/mid-prototype.md"
          - Protótipo de alta fidelidade: "project/high-prototype.md"
          - Teste de usabilidade: "project/usability-test.md"
  - Gerência:
      - Plano metodológico:
          - Plano metodológico: "management/methodology-plan.md"
          - Plano de comunicação: "management/communication-plan.md"
      - Roadmap do Produto: "management/product-roadmap.md"
      - Reuniões com Usuários:
          - Reunião 1: "management/po-meetings/meeting-1.md"
  - Pontos de Controle:
      - Ponto de Controle 1: "releases/release-1.md"