# Project information
site_name: "IHC - Fórum TutorBrasil"
site_author: "Grupo 07"
site_url: "https://luisgaboardi.github.io/Forum-TutorBrasil"

# Repository
repo_name: "Fórum TutorBrasil"
repo_url: "https://github.com/luisgaboardi/Forum-TutorBrasil"

theme:
  logo: ''
  favicon: ''
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
  language: "pt"
  name: "material"
  palette:
    primary: "green"
    accent: "black"

# Content Menu
nav:
  - Home: 'index.md'
  - Projeto:
      - Backlog: "project/product-backlog.md"
      - Personas: "project/personas.md"
      - Design:
          - Protótipo de baixa fidelidade: "project/low-prototype.md"
          - Protótipo de média fidelidade: "project/mid-prototype.md"
          - Protótipo de alta fidelidade: "project/high-prototype.md"
      - Comunidade:
          - Código de conduta: "project/CODE_OF_CONDUCT.md"
          - Diretrizes de contribuição: "project/CONTRIBUTING.md"
      - Questionários com Usuários:
          - Questionário 1: "project/surveys/survey-01.md"
  - Gerência:
      - Plano metodológico:
          - Plano metodológico: "management/methodology-plan.md"
          - Plano de comunicação: "management/communication-plan.md"
      - Roadmap do Produto: "management/product-roadmap.md"
  - Pontos de Controle:
      - 1º Ponto de Controle: "releases/release-0.md"
      - 2º Ponto de Controle: "releases/release-1.md"